# Site settings
title: Abraxas
description: Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alenicheva Alisa
user_description: I'm Master Student in Skoltech, Information Science&Technology program. My professional interests vary from Physics and Biotechnology to Data Science and Design, however at the moment I've rooted in ML&DL applications in Drug Discovery and Natural Language Processing. 
user_title: Skoltech Master Student
email: alisa.alenicheva@skoltech.ru
# twitter_username: lorem_ipsum
github_username:  korney3
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
