# Site settings
title: Alenicheva Alisa
description: Resume
baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alenicheva Alisa
user_description: I'm Researcher in Machine Learning Applications and Deep Learning in JetBrains Research. My professional interests vary from Physics and Biotechnology to Data Science and Design, however at the moment I've rooted in ML&DL applications in Drug Discovery. 
user_title: Machine Learning Researcher
email: koren.iz3x@yandex.ru
# twitter_username: korney34
github_username:  korney3
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
